app/admin/urls.py
from django.conf.urls import url

from . import views

app_name = 'admin'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^web-requests/$', views.web_requests, name='web_requests'),
    url(r'^book-logs/$', views.book_logs, name='book_logs'),
]

app/site/urls.py
from django.conf.urls import url

from . import views

app_name = 'site'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^add/$', views.add_book, name='add_book'),
    url(r'^(?P<pk>\d+)/$', views.book_detail, name='book_detail'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete_book, name='delete_book'),
]

app/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', include('app.admin.urls')),
    url(r'^', include('app.site.urls')),
]

config/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path(r'', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/site/forms.py
from datetime import date

from django import forms
from django.core.exceptions import ValidationError, ObjectDoesNotExist

from core.models import Book, Author

__all__ = (
    'BaseAuthorFormSet',
    'AuthorForm',
    'BookForm',
    'delete_book',
)


class BaseAuthorFormSet(forms.BaseFormSet):

    def __init__(self, *args, **kwargs):
        self.instances = kwargs.pop('instances', [])
        super(BaseAuthorFormSet, self).__init__(*args, **kwargs)

    def get_form_kwargs(self, index):
        form_kwargs = super(BaseAuthorFormSet, self).get_form_kwargs(index)
        if index < len(self.instances):
            form_kwargs['instance'] = self.instances[index]
        return form_kwargs

    def clean(self):
        if any(self.errors):
            return
        authors_name = []
        for form in self.forms:
            full_name = form.cleaned_data.get('full_name', '')
            if full_name in authors_name:
                raise ValidationError("Authors of the book is duplicated.")
            authors_name.append(full_name)

    def add_authors_to(self, book):
        authors = []

        for form in self.forms:
            author_data = form.cleaned_data
            full_name = author_data.get('full_name', '')
            info = author_data.get('info', '')
            try:
                author = Author.objects.get(full_name=full_name)
                if info:
                    author.info = info
                    author.save()
            except ObjectDoesNotExist:
                author = Author(**author_data)
                author.save()
            authors.append(author)

        book.set_authors(authors)


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['full_name', 'info']

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'isbn', 'price', 'publish_date']

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        if self.initial:
            self.initial.update({
                'publish_date': self.instance.get_publish_date,
            })

    def clean_publish_date(self):
        publish_date = self.cleaned_data['publish_date']
        if publish_date > date.today():
            raise ValidationError("The book should already be published.")
        return publish_date

app/site/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.forms import formset_factory
from django.http import Http404
from django.shortcuts import render, redirect

from core.models import Book
from .forms import BookForm, AuthorForm, BaseAuthorFormSet

__all__ = (
    'home',
    'add_book',
    'book_detail',
    'delete_book',
)


def home(request):
    template_name = 'site/content/home.html'
    context = {
        'books': Book.objects.all()
    }
    return render(request, template_name, context)


def add_book(request):
    template_name = 'site/content/book.html'
    AuthorFormSet = formset_factory(AuthorForm, formset=BaseAuthorFormSet, min_num=1, validate_min=True, extra=0)

    if request.method == 'POST':
        form = BookForm(request.POST)
        formset = AuthorFormSet(request.POST)
        if form.is_valid() and formset.is_valid():
            book = form.save()
            formset.add_authors_to(book)
            return redirect('site:home')
    else:
        form = BookForm()
        formset = AuthorFormSet()

    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, template_name, context)


def book_detail(request, pk):
    template_name = 'site/content/book.html'
    try:
        book = Book.objects.get(pk=pk)
    except ObjectDoesNotExist:
        raise Http404
    book_authors = book.authors.all()

    extra_forms = book_authors.count() - 1
    extra_forms = 0 if extra_forms < 0 else extra_forms
    AuthorFormSet = formset_factory(
        AuthorForm, formset=BaseAuthorFormSet,
        min_num=1, validate_min=True, extra=extra_forms
    )
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        formset = AuthorFormSet(request.POST)
        if form.is_valid() and formset.is_valid():
            book = form.save()
            formset.add_authors_to(book)
            return redirect('site:home')
    else:
        form = BookForm(instance=book)
        formset = AuthorFormSet(instances=book_authors)

    context = {
        'form': form,
        'formset': formset,
        'book': book,
    }
    return render(request, template_name, context)


def delete_book(request, pk):
    try:
        book = Book.objects.get(pk=pk)
    except ObjectDoesNotExist:
        raise Http404

    book.delete()
    return redirect('site:home')

templates/site/base.html
{% extends 'base.html' %}

{% block styles %}
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}site/css/main.css">{% endblock %}

{% block main_container %}
    {% include 'site/header.html' %}
    {% block content %}{% endblock %}
    {% include 'site/footer.html' %}
{% endblock %}

{% block scripts %}
    <script src="{{ STATIC_PREFIX }}site/js/main.js"></script>{% endblock %}

templates/site/footer.html
{% load static %}{% get_static_prefix as STATIC_PREFIX %}
{% load core_extras %}

<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <span class="text-muted">{% copyright_year %}</span>
  </div>
</footer>

templates/site/header.html
{% load static %}{% get_static_prefix as STATIC_PREFIX %}

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'site:home' %}">BookStore</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarCollapse"
                aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'site:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'site:add_book' %}">Add new book</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:home' %}">Admin Page</a>
                </li>
            </ul>
        </div>
    </nav>
</header>